#!/usr/bin/env bash
# shellcheck disable=SC1091
source ember_bash_setup &> /dev/null || { printf '%b' '\033[1;31m' >&2; echo "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd): The required dependency ember-shared could not be found (or ember_bash_setup could not be sourced for some other reason)." >&2; printf '%b' '\033[0m' >&2; exit 1; }
#set -x

trap 'die "A fatal error was reported on ${BASH_SOURCE[0]} line ${LINENO} in $(pwd) at $(emdate)."' ERR

# Usage: build-book [--quick|--confirm] [--all]

cd /Ember/ember-web-site
eogup-single

quick="false"
if [[ "--quick" == "$1" ]]; then
    quick="true"
    shift
elif [[ "--confirm" == "$1" ]]; then
    quick="confirm"
    shift
fi

all="false"
if [[ "--all" == "$1" ]]; then
    all="true"
fi

[[ "false" == "$quick" ]] && die "Pass --confirm to confirm you really want to build a bunch of rather large book files! Or pass --quick to only build the small ones."

buildBook() {
    if [[ "true" == "$quick" ]]; then
        /Ember\ Library/Ember\ satellite\ projects/futuramerlin-web-toolkit/scripts/futuramerlin-web-toolkit-build-book --native-targets-only "$1"
    else
        /Ember\ Library/Ember\ satellite\ projects/futuramerlin-web-toolkit/scripts/futuramerlin-web-toolkit-build-book "$1"
    fi
}

buildBook "ember.fmwtk-book.conf"
buildBook "ember-subset.fmwtk-book.conf"

# Sub-books
buildBook "library/library.fmwtk-book.conf"
buildBook "specification/community/community.fmwtk-book.conf"
buildBook "specification/specification.fmwtk-book.conf"
buildBook "specification/engineering-and-tech/information-technology/software/eite.fmwtk-book.conf"
if [[ "true" == "$all" ]]; then
    buildBook "ancillary/docs.fmwtk-book.conf"
    buildBook "people/elli/writings/story/story.fmwtk-book.conf"

    # Extra: big book!
    buildBook "people/elli/writings/collected.fmwtk-book.conf"
fi

# Copy finished books
./.futuramerlin-web-toolkit/post-book-hooks
