#!/bin/bash

rm -r subbooks
mkdir subbooks
find . -path ./subbooks -prune -o -path ./futuramerlin-web-toolkit-output -o -path ./.egup.stat -prune -o \( -type d -and -name '*.fmwtk-book' -exec cp -r {} ./subbooks/ \; \)
